### ISSUE TITLE
GitHub Action workflows should not be included when using the repository template

### ISSUE THREAD

**Issue by caendesilva** [hydephp/hyde#233]
### Issue description

Issue to track a bug in GitHub, where it's not possible to exclude files from repository templates. See https://github.com/orgs/community/discussions/22183

In this template, we run tests on the project, but the workflow shouldn't be present in the release when users create a repo based on the template. I don't want to use up their action minutes for something that they don't need. Considering forks don't even run workflows by default, why would repo templates be different?

**Comment by caendesilva** [comment]
#### One possible fix is to add another workflow

```yaml
# filepath .github/workflows/first-time-setup.yml

name: first-time-setup
run-name: first time setup of repo

on:
  # run when branch created (repo generated from template)
  create:

# only keep latest run of this workflow
concurrency:
  group: first-time-setup
  cancel-in-progress: true

permissions: 
  actions: write
  checks: write
  contents: write
  
jobs:
  first-time-setup:
    # ensure run only once, when repo generated
    if: github.run_number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove unneeded files
        run: rm -rf .github/workflows
        
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Setup repo"
```

This does this:

![image](https://github.com/hydephp/hyde/assets/95144705/cf590e18-3243-4904-9771-999b54b006ac)

But it doesn't feel right. Maybe a better solution is to just not run the workflow outside the repo.
